self-hosted-runner:
  labels:
    - axis
    - trusted

paths:
  .github/workflows/*.lock.yml:
    ignore:
      - '.*'
  .github/workflows/refresh-current-state.yml:
    ignore:
      - 'constant expression "false" in condition'

