package axismcp

import (
	"context"
	"fmt"
	"os"
	"time"

	mcpproto "github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"
	"github.com/toasterbook88/axis/internal/models"
	"github.com/toasterbook88/axis/internal/reservation"
)

func registerTriangleTools(s *mcpserver.MCPServer, useCache bool, cacheAddr string) {
	s.AddTool(
		mcpproto.NewTool(
			"triangle_request_lease",
			mcpproto.WithDescription("Request an advisory resource lease on a specific node (advisory only)"),
			mcpproto.WithString(
				"node",
				mcpproto.Required(),
				mcpproto.Description("Target node name for the reservation"),
			),
			mcpproto.WithString(
				"owner_exec_id",
				mcpproto.Required(),
				mcpproto.Description("Unique crew/execution session ID"),
			),
			mcpproto.WithString(
				"owner_surface",
				mcpproto.Required(),
				mcpproto.Description("Name of the agent or surface requesting the lease (e.g., 'Grok', 'Hermes')"),
			),
			mcpproto.WithInteger(
				"ram_mb",
				mcpproto.Required(),
				mcpproto.Description("Amount of RAM in MB to reserve"),
			),
			mcpproto.WithString(
				"id",
				mcpproto.Description("Optional unique reservation ID (autogenerated if not specified)"),
			),
			mcpproto.WithInteger(
				"vram_mb",
				mcpproto.Description("Optional amount of VRAM in MB to reserve"),
			),
			mcpproto.WithInteger(
				"duration_seconds",
				mcpproto.Description("Optional lease duration in seconds (computed from now if specified)"),
			),
			mcpproto.WithString(
				"description",
				mcpproto.Description("Optional descriptive purpose for the lease"),
			),
		),
		func(ctx context.Context, req mcpproto.CallToolRequest) (*mcpproto.CallToolResult, error) {
			return triangleRequestLeaseTool(ctx, req, useCache, cacheAddr)
		},
	)

	s.AddTool(
		mcpproto.NewTool(
			"triangle_release_lease",
			mcpproto.WithDescription("Release an active advisory resource lease (advisory only)"),
			mcpproto.WithString(
				"id",
				mcpproto.Required(),
				mcpproto.Description("The reservation ID to release"),
			),
		),
		func(ctx context.Context, req mcpproto.CallToolRequest) (*mcpproto.CallToolResult, error) {
			return triangleReleaseLeaseTool(ctx, req)
		},
	)

	s.AddTool(
		mcpproto.NewTool(
			"triangle_heartbeat_lease",
			mcpproto.WithDescription("Send a heartbeat for an active advisory resource lease (advisory only)"),
			mcpproto.WithString(
				"id",
				mcpproto.Required(),
				mcpproto.Description("The reservation ID to heartbeat"),
			),
		),
		func(ctx context.Context, req mcpproto.CallToolRequest) (*mcpproto.CallToolResult, error) {
			return triangleHeartbeatLeaseTool(ctx, req)
		},
	)
}

func populateLedgerCapacity(ledger *reservation.Ledger, snap *models.ClusterSnapshot) {
	for _, n := range snap.Nodes {
		if n.Resources != nil {
			ledger.SetNodeCapacity(n.Name, n.Resources.RAMTotalMB)
		}
	}
}

func triangleRequestLeaseTool(ctx context.Context, req mcpproto.CallToolRequest, useCache bool, cacheAddr string) (*mcpproto.CallToolResult, error) {
	node, err := req.RequireString("node")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}
	ownerExecID, err := req.RequireString("owner_exec_id")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}
	ownerSurface, err := req.RequireString("owner_surface")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}
	ramMB, err := req.RequireInt("ram_mb")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}

	id := req.GetString("id", "")
	vramMB := req.GetInt("vram_mb", 0)
	durationSeconds := req.GetInt("duration_seconds", 0)
	description := req.GetString("description", "")

	// 1. Expiry Validation
	if durationSeconds <= 0 {
		durationSeconds = 120 // Default to 2 minutes
	}

	ledger := reservation.NewLedger(reservation.DefaultLimits(), nil)

	// 2. Lock Transaction
	if err := ledger.LockFile(ctx); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to acquire ledger lock: %v", err)), nil
	}
	defer ledger.UnlockFile()

	if err := ledger.Load(); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to load ledger: %v", err)), nil
	}

	// 3. Snapshot and Staleness Check
	snap, err := currentSnapshot(ctx, useCache, cacheAddr)
	if err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to get cluster snapshot: %v", err)), nil
	}

	if !snap.Timestamp.IsZero() {
		threshold := 30 * time.Second
		if val := os.Getenv("AXIS_LEASE_STALENESS_THRESHOLD"); val != "" {
			if d, err := time.ParseDuration(val); err == nil {
				threshold = d
			}
		}
		if time.Since(snap.Timestamp) > threshold {
			return mcpproto.NewToolResultError(fmt.Sprintf("cluster snapshot is stale (age: %v, threshold: %v); lease request rejected to prevent overcommit", time.Since(snap.Timestamp).Round(time.Second), threshold)), nil
		}
	}

	populateLedgerCapacity(ledger, snap)

	if id == "" {
		id = models.GenerateID("lease")
	}

	expiresAt := time.Now().UTC().Add(time.Duration(durationSeconds) * time.Second)

	entry := reservation.Entry{
		ID:           id,
		Node:         node,
		OwnerExecID:  ownerExecID,
		OwnerSurface: ownerSurface,
		RAMMB:        int64(ramMB),
		VRAMMB:       int64(vramMB),
		ExpiresAt:    expiresAt,
		Description:  description,
	}

	reserved, err := ledger.Reserve(entry)
	if err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("reservation failed: %v", err)), nil
	}

	return mcpproto.NewToolResultJSON(reserved)
}

func triangleReleaseLeaseTool(ctx context.Context, req mcpproto.CallToolRequest) (*mcpproto.CallToolResult, error) {
	id, err := req.RequireString("id")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}

	ledger := reservation.NewLedger(reservation.DefaultLimits(), nil)

	// Lock Transaction
	if err := ledger.LockFile(ctx); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to acquire ledger lock: %v", err)), nil
	}
	defer ledger.UnlockFile()

	if err := ledger.Load(); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to load ledger: %v", err)), nil
	}

	if err := ledger.Release(id); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to release lease: %v", err)), nil
	}

	return mcpproto.NewToolResultJSON(map[string]any{
		"success": true,
		"id":      id,
	})
}

func triangleHeartbeatLeaseTool(ctx context.Context, req mcpproto.CallToolRequest) (*mcpproto.CallToolResult, error) {
	id, err := req.RequireString("id")
	if err != nil {
		return mcpproto.NewToolResultError(err.Error()), nil
	}

	ledger := reservation.NewLedger(reservation.DefaultLimits(), nil)

	// Lock Transaction
	if err := ledger.LockFile(ctx); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to acquire ledger lock: %v", err)), nil
	}
	defer ledger.UnlockFile()

	if err := ledger.Load(); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to load ledger: %v", err)), nil
	}

	if err := ledger.Heartbeat(id); err != nil {
		return mcpproto.NewToolResultError(fmt.Sprintf("failed to heartbeat lease: %v", err)), nil
	}

	return mcpproto.NewToolResultJSON(map[string]any{
		"success": true,
		"id":      id,
	})
}
