name: govulncheck

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

      - name: Run govulncheck
        run: govulncheck ./...
